# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
asphalt = "jackTabsCode/asphalt@1.2.0"
lune = "lune-org/lune@0.10.4"
